#!/bin/bash

# Download PHPCS
mkdir bin
cd bin
curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar

# Clone Drupal Coder repo
mkdir drupal
cd drupal
git clone https://git.drupalcode.org/project/coder.git
cd ..
cd ..

# Give executable permission to PHPCS
chmod +x bin/phpcs.phar
