<?php

/**
 * @file
 * Exported quotations saved search.
 */

$mgd = [
    [
      'name' => 'SavedSearch_Civicase_Quotations',
      'entity' => 'SavedSearch',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'name' => 'Civicase_Quotations',
          'label' => 'Civicase Quotations',
          'form_values' => NULL,
          'search_custom_id' => NULL,
          'api_entity' => 'CaseSalesOrder',
          'api_params' => [
            'version' => 4,
            'select' => [
              'id',
              'client_id.display_name',
              'DATE(quotation_date) AS DATE_quotation_date',
              'description',
              'owner_id.display_name',
              'CONCAT_WS(" ", total_before_tax, currency:label) AS CONCAT_WS_total_before_tax_currency_label',
              'CONCAT_WS(" ", total_after_tax, currency:label) AS CONCAT_WS_total_after_tax_currency_label',
              'status_id:label',
              'case_id',
            ],
            'orderBy' => [
              'created_at' => 'DESC',
            ],
            'where' => [],
            'groupBy' => [],
            'join' => [],
            'having' => [],
            'limit' => 10,
          ],
          'expires_date' => NULL,
          'description' => NULL,
          'mapping_id' => NULL,
        ],
      ],
    ],
    [
      'name' => 'SavedSearch_Civicase_Quotations_SearchDisplay_Civicase_Contact_Quotations_Table',
      'entity' => 'SearchDisplay',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'name' => 'Civicase_Contact_Quotations_Table',
          'label' => 'Contact Quotations List',
          'saved_search_id.name' => 'Civicase_Quotations',
          'type' => 'table',
          'settings' => [
            'actions' => TRUE,
            'limit' => 10,
            'classes' => [
              'table',
              'table-striped',
            ],
            'pager' => [],
            'placeholder' => 5,
            'sort' => [
              [
                'created_at',
                'DESC',
              ],
            ],
            'columns' => [
              [
                'type' => 'field',
                'key' => 'id',
                'dataType' => 'Integer',
                'label' => 'ID',
                'sortable' => TRUE,
                'alignment' => '',
              ],
              [
                'type' => 'field',
                'key' => 'case_id',
                'dataType' => 'Integer',
                'label' => 'Prospect Id',
                'sortable' => TRUE,
                'link' => [
                  'path' => 'civicrm/contact/view/case?reset=1&id=[case_id]&cid=[user_contact_id]&action=view&context=dashboard&selectedChild=case',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                ],
                'alignment' => '',
              ],
              [
                'type' => 'field',
                'key' => 'DATE_quotation_date',
                'dataType' => 'Date',
                'label' => 'Date',
                'sortable' => TRUE,
                'alignment' => '',
              ],
              [
                'type' => 'field',
                'key' => 'owner_id.display_name',
                'dataType' => 'String',
                'label' => 'Owner',
                'sortable' => TRUE,
                'link' => [
                  'path' => '',
                  'entity' => 'Contact',
                  'action' => 'view',
                  'join' => 'owner_id',
                  'target' => '_blank',
                ],
                'title' => 'View Owner',
                'alignment' => '',
              ],
              [
                'type' => 'field',
                'key' => 'CONCAT_WS_total_before_tax_currency_label',
                'dataType' => 'String',
                'label' => 'Total Before Tax',
                'sortable' => TRUE,
                'alignment' => '',
              ],
              [
                'type' => 'field',
                'key' => 'CONCAT_WS_total_after_tax_currency_label',
                'dataType' => 'String',
                'label' => 'Total After Tax',
                'sortable' => TRUE,
                'alignment' => '',
              ],
              [
                'type' => 'field',
                'key' => 'status_id:label',
                'dataType' => 'Integer',
                'label' => 'Status',
                'sortable' => TRUE,
                'alignment' => '',
              ],
              [
                'text' => '',
                'style' => 'default',
                'size' => 'btn-sm',
                'icon' => 'fa-bars',
                'links' => [
                  [
                    'path' => '',
                    'icon' => 'fa-external-link',
                    'text' => 'View',
                    'style' => 'default',
                    'condition' => [],
                    'entity' => 'CaseSalesOrder',
                    'action' => 'view',
                    'join' => '',
                    'target' => '_blank',
                  ],
                  [
                    'entity' => 'CaseSalesOrder',
                    'action' => 'update',
                    'join' => '',
                    'target' => '_blank',
                    'icon' => 'fa-pencil',
                    'text' => 'Edit',
                    'style' => 'default',
                    'path' => '',
                    'condition' => [],
                  ],
                  [
                    'entity' => 'CaseSalesOrder',
                    'action' => 'delete',
                    'join' => '',
                    'target' => 'crm-popup',
                    'icon' => 'fa-trash',
                    'text' => 'Delete',
                    'style' => 'default',
                    'path' => '',
                    'condition' => [],
                  ],
                  [
                    'path' => 'civicrm/case-features/quotations/download-pdf?id=[id]',
                    'icon' => 'fa-file-pdf-o',
                    'text' => 'Download PDF',
                    'style' => 'default',
                    'condition' => [],
                    'entity' => '',
                    'action' => '',
                    'join' => '',
                    'target' => '_blank',
                  ],
                  [
                    'path' => 'civicrm/case-features/quotations/create-contribution?id=[id]',
                    'icon' => 'fa-credit-card',
                    'text' => 'Create Contribution',
                    'style' => 'default',
                    'condition' => [],
                    'entity' => '',
                    'action' => '',
                    'join' => '',
                    'target' => 'crm-popup',
                  ],
                  [
                    'path' => 'civicrm/case-features/quotations/email?id=[id]',
                    'icon' => 'fa-paper-plane-o',
                    'text' => 'Send By Email',
                    'style' => 'default',
                    'condition' => [],
                    'entity' => '',
                    'action' => '',
                    'join' => '',
                    'target' => 'crm-popup',
                  ],
                ],
                'type' => 'menu',
                'alignment' => '',
                'label' => 'Actions',
              ],
            ],
            'noResultsText' => 'No quotations found',
          ],
          'acl_bypass' => FALSE,
        ],
      ],
    ],
    [
      'name' => 'SavedSearch_Civicase_Quotations_SearchDisplay_Civicase_Quotations_Table',
      'entity' => 'SearchDisplay',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'name' => 'Civicase_Quotations_Table',
          'label' => 'Quotations List',
          'saved_search_id.name' => 'Civicase_Quotations',
          'type' => 'table',
          'settings' => [
            'actions' => TRUE,
            'limit' => 10,
            'classes' => [
              'table',
              'table-striped',
            ],
            'pager' => [],
            'placeholder' => 5,
            'sort' => [
              [
                'created_at',
                'DESC',
              ],
            ],
            'columns' => [
              [
                'type' => 'field',
                'key' => 'id',
                'dataType' => 'Integer',
                'label' => 'ID',
                'sortable' => TRUE,
                'alignment' => '',
              ],
              [
                'type' => 'field',
                'key' => 'client_id.display_name',
                'dataType' => 'String',
                'label' => 'Client',
                'sortable' => TRUE,
                'link' => [
                  'path' => '',
                  'entity' => 'Contact',
                  'action' => 'view',
                  'join' => 'client_id',
                  'target' => '_blank',
                ],
                'title' => 'View Client',
                'alignment' => '',
              ],
              [
                'type' => 'field',
                'key' => 'DATE_quotation_date',
                'dataType' => 'Date',
                'label' => 'Date',
                'sortable' => TRUE,
                'alignment' => '',
              ],
              [
                'type' => 'field',
                'key' => 'owner_id.display_name',
                'dataType' => 'String',
                'label' => 'Owner',
                'sortable' => TRUE,
                'link' => [
                  'path' => '',
                  'entity' => 'Contact',
                  'action' => 'view',
                  'join' => 'owner_id',
                  'target' => '_blank',
                ],
                'title' => 'View Owner',
                'alignment' => '',
              ],
              [
                'type' => 'field',
                'key' => 'CONCAT_WS_total_before_tax_currency_label',
                'dataType' => 'String',
                'label' => 'Total Before Tax',
                'sortable' => TRUE,
                'alignment' => '',
              ],
              [
                'type' => 'field',
                'key' => 'CONCAT_WS_total_after_tax_currency_label',
                'dataType' => 'String',
                'label' => 'Total After Tax',
                'sortable' => TRUE,
                'alignment' => '',
              ],
              [
                'type' => 'field',
                'key' => 'status_id:label',
                'dataType' => 'Integer',
                'label' => 'Status',
                'sortable' => TRUE,
                'alignment' => '',
              ],
              [
                'text' => '',
                'style' => 'default',
                'size' => 'btn-sm',
                'icon' => 'fa-bars',
                'links' => [
                  [
                    'path' => '',
                    'icon' => 'fa-external-link',
                    'text' => 'View',
                    'style' => 'default',
                    'condition' => [],
                    'entity' => 'CaseSalesOrder',
                    'action' => 'view',
                    'join' => '',
                    'target' => '_blank',
                  ],
                  [
                    'entity' => 'CaseSalesOrder',
                    'action' => 'update',
                    'join' => '',
                    'target' => '_blank',
                    'icon' => 'fa-pencil',
                    'text' => 'Edit',
                    'style' => 'default',
                    'path' => '',
                    'condition' => [],
                  ],
                  [
                    'entity' => 'CaseSalesOrder',
                    'action' => 'delete',
                    'join' => '',
                    'target' => 'crm-popup',
                    'icon' => 'fa-trash',
                    'text' => 'Delete',
                    'style' => 'default',
                    'path' => '',
                    'condition' => [],
                  ],
                  [
                    'path' => 'civicrm/case-features/quotations/download-pdf?id=[id]',
                    'icon' => 'fa-file-pdf-o',
                    'text' => 'Download PDF',
                    'style' => 'default',
                    'condition' => [],
                    'entity' => '',
                    'action' => '',
                    'join' => '',
                    'target' => '_blank',
                  ],
                  [
                    'path' => 'civicrm/case-features/quotations/create-contribution?id=[id]',
                    'icon' => 'fa-credit-card',
                    'text' => 'Create Contribution',
                    'style' => 'default',
                    'condition' => [],
                    'entity' => '',
                    'action' => '',
                    'join' => '',
                    'target' => 'crm-popup',
                  ],
                  [
                    'path' => 'civicrm/case-features/quotations/email?id=[id]',
                    'icon' => 'fa-paper-plane-o',
                    'text' => 'Send By Email',
                    'style' => 'default',
                    'condition' => [],
                    'entity' => '',
                    'action' => '',
                    'join' => '',
                    'target' => 'crm-popup',
                  ],
                ],
                'type' => 'menu',
                'alignment' => '',
                'label' => 'Actions',
              ],
            ],
            'noResultsText' => 'No quotations found',
          ],
          'acl_bypass' => FALSE,
        ],
      ],
    ],
    [
      'name' => 'SavedSearch_Quotation_Invoices',
      'entity' => 'SavedSearch',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'name' => 'Quotation_Invoices',
          'label' => 'Quotation Invoices',
          'form_values' => NULL,
          'search_custom_id' => NULL,
          'api_entity' => 'CaseSalesOrderContribution',
          'api_params' => [
            'version' => 4,
            'select' => [
              'id',
              'CaseSalesOrderContribution_Contribution_contribution_id_01.id',
              'CaseSalesOrderContribution_Contribution_contribution_id_01.financial_type_id:label',
              'CaseSalesOrderContribution_Contribution_contribution_id_01.total_amount',
              'CaseSalesOrderContribution_Contribution_contribution_id_01.source',
              'CaseSalesOrderContribution_Contribution_contribution_id_01.thankyou_date',
              'CaseSalesOrderContribution_Contribution_contribution_id_01.contribution_status_id:label',
              'CaseSalesOrderContribution_Contribution_contribution_id_01.receive_date',
            ],
            'orderBy' => [],
            'where' => [],
            'groupBy' => [],
            'join' => [
              [
                'Contribution AS CaseSalesOrderContribution_Contribution_contribution_id_01',
                'LEFT',
                [
                  'contribution_id',
                  '=',
                  'CaseSalesOrderContribution_Contribution_contribution_id_01.id',
                ],
              ],
              [
                'CaseSalesOrder AS CaseSalesOrderContribution_CaseSalesOrder_case_sales_order_id_01',
                'LEFT',
                [
                  'case_sales_order_id',
                  '=',
                  'CaseSalesOrderContribution_CaseSalesOrder_case_sales_order_id_01.id',
                ],
              ],
            ],
            'having' => [],
          ],
          'expires_date' => NULL,
          'description' => NULL,
          'mapping_id' => NULL,
        ],
      ],
    ],
    [
      'name' => 'SavedSearch_Quotation_Invoices_SearchDisplay_Quotation_Invoices',
      'entity' => 'SearchDisplay',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'name' => 'Quotation_Invoices',
          'label' => 'Quotation Invoices',
          'saved_search_id.name' => 'Quotation_Invoices',
          'type' => 'table',
          'settings' => [
            'actions' => FALSE,
            'limit' => 10,
            'classes' => [
              'table',
              'table-striped',
            ],
            'pager' => [],
            'placeholder' => 5,
            'sort' => [],
            'columns' => [
              [
                'type' => 'field',
                'key' => 'CaseSalesOrderContribution_Contribution_contribution_id_01.total_amount',
                'dataType' => 'Money',
                'label' => 'Amount',
                'sortable' => TRUE,
              ],
              [
                'type' => 'field',
                'key' => 'CaseSalesOrderContribution_Contribution_contribution_id_01.financial_type_id:label',
                'dataType' => 'Integer',
                'label' => 'Type',
                'sortable' => TRUE,
              ],
              [
                'type' => 'field',
                'key' => 'CaseSalesOrderContribution_Contribution_contribution_id_01.source',
                'dataType' => 'String',
                'label' => 'Source',
                'sortable' => TRUE,
              ],
              [
                'type' => 'field',
                'key' => 'CaseSalesOrderContribution_Contribution_contribution_id_01.receive_date',
                'dataType' => 'Timestamp',
                'label' => 'Date',
                'sortable' => TRUE,
              ],
              [
                'type' => 'field',
                'key' => 'CaseSalesOrderContribution_Contribution_contribution_id_01.thankyou_date',
                'dataType' => 'Timestamp',
                'label' => 'Thank-You Sent',
                'sortable' => TRUE,
                'rewrite' => '{if "[CaseSalesOrderContribution_Contribution_contribution_id_01.thankyou_date]"} Yes {else} No {/if}',
              ],
              [
                'type' => 'field',
                'key' => 'CaseSalesOrderContribution_Contribution_contribution_id_01.contribution_status_id:label',
                'dataType' => 'Integer',
                'label' => 'Status',
                'sortable' => TRUE,
              ],
              [
                'text' => 'Actions',
                'style' => 'default',
                'size' => 'btn-sm',
                'icon' => 'fa-bars',
                'links' => [
                  [
                    'entity' => 'Contribution',
                    'action' => 'view',
                    'join' => 'CaseSalesOrderContribution_Contribution_contribution_id_01',
                    'target' => 'crm-popup',
                    'icon' => 'fa-external-link',
                    'text' => 'View',
                    'style' => 'default',
                    'path' => '',
                    'condition' => [],
                  ],
                  [
                    'entity' => 'Contribution',
                    'action' => 'update',
                    'join' => 'CaseSalesOrderContribution_Contribution_contribution_id_01',
                    'target' => 'crm-popup',
                    'icon' => 'fa-pencil',
                    'text' => 'Edit',
                    'style' => 'default',
                    'path' => '',
                    'condition' => [],
                  ],
                ],
                'type' => 'menu',
                'alignment' => 'text-right',
              ],
            ],
            'noResultsText' => 'No Invoices found',
          ],
          'acl_bypass' => FALSE,
        ],
      ],
    ],
];


$searchKitIsInstalled = 'installed' ===
CRM_Extension_System::singleton()->getManager()->getStatus('org.civicrm.search_kit');
if ($searchKitIsInstalled) {
  return $mgd;
}

return [];
