<?php

/**
 * Class CRM_Civicase_Page_CaseSalesOrder.
 *
 * Define an Angular page for Case Sales Order view.
 */
class CRM_Civicase_Page_CaseSalesOrder extends CRM_Core_Page {

  /**
   * Run Function.
   *
   * Sets variables required by the Page template.
   *
   * @return string
   *   The content generated by running this page
   */
  public function run() {
    /** @var \Civi\Angular\AngularLoader $loader */
    $loader = Civi::service('angularjs.loader');
    $loader->addModules(['crmApp', 'civicase-features']);
    $salesOrderId = CRM_Utils_Request::retrieveValue('id', 'Positive');
    $this->assign('sales_order_id', $salesOrderId);

    return parent::run();
  }

}
