<?php

use Civi\Angular\Manager;

/**
 * Class CRM_Civicase_Page_ContactActivityTab.
 *
 * Implement the Angular version of the tab "View Contact => Cases".
 */
class CRM_Civicase_Page_ContactCaseTab extends CRM_Core_Page {

  /**
   * Run Function.
   *
   * Sets variables required by the Page template.
   *
   * @return string
   *   The content generated by running this page
   */
  public function run() {
    $caseTypeCategory = CRM_Utils_Request::retrieveValue('case_type_category', 'String');
    $this->assign('case_type_category', $caseTypeCategory);
    $caseCategoryName = CRM_Civicase_Helper_CaseCategory::getCaseCategoryNameFromOptionValue($caseTypeCategory);
    CRM_Civicase_Hook_Helper_CaseTypeCategory::addWordReplacements($caseCategoryName);

    // Skip translations for default case category:
    if (strtolower($caseCategoryName) == 'cases') {
      CRM_Core_Resources::singleton()->addSetting([
        'strings::uk.co.compucorp.civicase' => [],
      ]);

      return parent::run();
    }

    $angularManager = new Manager(CRM_Core_Resources::singleton());
    $civicaseModule = $angularManager->getModule('civicase');
    $translations = $angularManager->getTranslatedStrings('civicase');

    // Adds translated civicase settings and strings to global CRM var:
    CRM_Core_Resources::singleton()->addSetting([
      'civicase' => $civicaseModule['settings'],
    ]);
    CRM_Core_Resources::singleton()->addSetting([
      'strings::uk.co.compucorp.civicase' => $translations,
    ]);

    return parent::run();
  }

}
