<?php

/**
 * Class CRM_Civicase_Page_ContactCaseSalesOrderTab.
 *
 * Returns page that list quotations belonging to a contact.
 */
class CRM_Civicase_Page_ContactCaseSalesOrderTab extends CRM_Core_Page {

  /**
   * Run Function.
   *
   * Sets variables required by the Page template.
   *
   * @return string
   *   The content generated by running this page
   */
  public function run() {
    /** @var \Civi\Angular\AngularLoader $loader */
    $loader = Civi::service('angularjs.loader');
    $loader->addModules(['crmApp', 'civicase-features']);
    $contactId = CRM_Utils_Request::retrieveValue('cid', 'Positive');
    $this->assign('contactId', $contactId);

    return parent::run();
  }

}
