<?php

use Civi\Angular\AngularLoader as AngularLoader;

/**
 * My Activities page.
 */
class CRM_Civicase_Page_MyActivities extends CRM_Core_Page {

  /**
   * Run Function.
   *
   * This function takes care of all the things common to all
   * pages. This typically involves assigning the appropriate
   * smarty variable :)
   *
   * @return string
   *   The content generated by running this page
   */
  public function run() {
    $loader = new AngularLoader();
    $loader->setPageName('civicrm/case/my-activities');
    $loader->setModules(['crmApp', 'my-activities']);
    $loader->load();

    CRM_Core_Resources::singleton()
      ->addScriptFile('uk.co.compucorp.civicase', 'packages/moment-with-locales.min.js');

    return parent::run();
  }

}
