<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from uk.co.compucorp.civicase/xml/schema/CRM/Civicase/CaseCategoryInstance.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:c54be94451d9f9473afcc991619787f0)
 */
use CRM_Civicase_ExtensionUtil as E;

/**
 * Database access object for the CaseCategoryInstance entity.
 */
class CRM_Civicase_DAO_CaseCategoryInstance extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_case_category_instance';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique CaseCategoryInstance Id
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * One of the values of the case_type_categories option group
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $category_id;

  /**
   * One of the values of the case_category_instance_type option group
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $instance_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_case_category_instance';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Case Category Instances') : E::ts('Case Category Instance');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique CaseCategoryInstance Id'),
          'required' => TRUE,
          'where' => 'civicrm_case_category_instance.id',
          'table_name' => 'civicrm_case_category_instance',
          'entity' => 'CaseCategoryInstance',
          'bao' => 'CRM_Civicase_DAO_CaseCategoryInstance',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'category_id' => [
          'name' => 'category_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('One of the values of the case_type_categories option group'),
          'required' => TRUE,
          'where' => 'civicrm_case_category_instance.category_id',
          'table_name' => 'civicrm_case_category_instance',
          'entity' => 'CaseCategoryInstance',
          'bao' => 'CRM_Civicase_DAO_CaseCategoryInstance',
          'localizable' => 0,
          'pseudoconstant' => [
            'optionGroupName' => 'case_type_categories',
            'optionEditPath' => 'civicrm/admin/options/case_type_categories',
          ],
          'add' => NULL,
        ],
        'instance_id' => [
          'name' => 'instance_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('One of the values of the case_category_instance_type option group'),
          'required' => TRUE,
          'where' => 'civicrm_case_category_instance.instance_id',
          'table_name' => 'civicrm_case_category_instance',
          'entity' => 'CaseCategoryInstance',
          'bao' => 'CRM_Civicase_DAO_CaseCategoryInstance',
          'localizable' => 0,
          'pseudoconstant' => [
            'optionGroupName' => 'case_category_instance_type',
            'optionEditPath' => 'civicrm/admin/options/case_category_instance_type',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'case_category_instance', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'case_category_instance', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'unique_category' => [
        'name' => 'unique_category',
        'field' => [
          0 => 'category_id',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_case_category_instance::1::category_id',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
