<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from uk.co.compucorp.civicase/xml/schema/CRM/Civicase/CaseSalesOrderLine.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:68a85389455a42d654dbb49ce271ada4)
 */
use CRM_Civicase_ExtensionUtil as E;

/**
 * Database access object for the CaseSalesOrderLine entity.
 */
class CRM_Civicase_DAO_CaseSalesOrderLine extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_case_sales_order_line';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique CaseSalesOrderLine ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to CaseSalesOrder
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $sales_order_id;

  /**
   * FK to CiviCRM Financial Type
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $financial_type_id;

  /**
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $product_id;

  /**
   * line item deesctiption
   *
   * @var string
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $item_description;

  /**
   * Quantity
   *
   * @var float|string|null
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $quantity;

  /**
   * Unit Price
   *
   * @var float|string|null
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $unit_price;

  /**
   * Tax rate for the line item
   *
   * @var float|string|null
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $tax_rate;

  /**
   * Discount applied to the line item
   *
   * @var float|string|null
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $discounted_percentage;

  /**
   * Quantity x Unit Price x (100-Discount)%
   *
   * @var float|string|null
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $subtotal_amount;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_case_sales_order_line';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Case Sales Order Lines') : E::ts('Case Sales Order Line');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'sales_order_id', 'civicrm_case_sales_order', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'financial_type_id', 'civicrm_financial_type', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'product_id', 'civicrm_product', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique CaseSalesOrderLine ID'),
          'required' => TRUE,
          'where' => 'civicrm_case_sales_order_line.id',
          'table_name' => 'civicrm_case_sales_order_line',
          'entity' => 'CaseSalesOrderLine',
          'bao' => 'CRM_Civicase_DAO_CaseSalesOrderLine',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'sales_order_id' => [
          'name' => 'sales_order_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to CaseSalesOrder'),
          'where' => 'civicrm_case_sales_order_line.sales_order_id',
          'table_name' => 'civicrm_case_sales_order_line',
          'entity' => 'CaseSalesOrderLine',
          'bao' => 'CRM_Civicase_DAO_CaseSalesOrderLine',
          'localizable' => 0,
          'FKClassName' => 'CRM_Civicase_DAO_CaseSalesOrder',
          'html' => [
            'type' => 'EntityRef',
          ],
          'add' => NULL,
        ],
        'financial_type_id' => [
          'name' => 'financial_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to CiviCRM Financial Type'),
          'where' => 'civicrm_case_sales_order_line.financial_type_id',
          'table_name' => 'civicrm_case_sales_order_line',
          'entity' => 'CaseSalesOrderLine',
          'bao' => 'CRM_Civicase_DAO_CaseSalesOrderLine',
          'localizable' => 0,
          'FKClassName' => 'CRM_Financial_DAO_FinancialType',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Financial Type"),
          ],
          'add' => NULL,
        ],
        'product_id' => [
          'name' => 'product_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Product ID'),
          'where' => 'civicrm_case_sales_order_line.product_id',
          'table_name' => 'civicrm_case_sales_order_line',
          'entity' => 'CaseSalesOrderLine',
          'bao' => 'CRM_Civicase_DAO_CaseSalesOrderLine',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contribute_DAO_Product',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Product"),
          ],
          'add' => NULL,
        ],
        'item_description' => [
          'name' => 'item_description',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Item Description'),
          'description' => E::ts('line item deesctiption'),
          'required' => FALSE,
          'where' => 'civicrm_case_sales_order_line.item_description',
          'table_name' => 'civicrm_case_sales_order_line',
          'entity' => 'CaseSalesOrderLine',
          'bao' => 'CRM_Civicase_DAO_CaseSalesOrderLine',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
            'label' => E::ts("Item Description"),
          ],
          'add' => NULL,
        ],
        'quantity' => [
          'name' => 'quantity',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Quantity'),
          'description' => E::ts('Quantity'),
          'precision' => [
            20,
            2,
          ],
          'where' => 'civicrm_case_sales_order_line.quantity',
          'table_name' => 'civicrm_case_sales_order_line',
          'entity' => 'CaseSalesOrderLine',
          'bao' => 'CRM_Civicase_DAO_CaseSalesOrderLine',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Quantity"),
          ],
          'add' => NULL,
        ],
        'unit_price' => [
          'name' => 'unit_price',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Unit Price'),
          'description' => E::ts('Unit Price'),
          'precision' => [
            20,
            2,
          ],
          'where' => 'civicrm_case_sales_order_line.unit_price',
          'table_name' => 'civicrm_case_sales_order_line',
          'entity' => 'CaseSalesOrderLine',
          'bao' => 'CRM_Civicase_DAO_CaseSalesOrderLine',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Unit Price"),
          ],
          'add' => NULL,
        ],
        'tax_rate' => [
          'name' => 'tax_rate',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Tax Rate'),
          'description' => E::ts('Tax rate for the line item'),
          'precision' => [
            20,
            2,
          ],
          'where' => 'civicrm_case_sales_order_line.tax_rate',
          'table_name' => 'civicrm_case_sales_order_line',
          'entity' => 'CaseSalesOrderLine',
          'bao' => 'CRM_Civicase_DAO_CaseSalesOrderLine',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Tax"),
          ],
          'add' => NULL,
        ],
        'discounted_percentage' => [
          'name' => 'discounted_percentage',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Discounted Percentage'),
          'description' => E::ts('Discount applied to the line item'),
          'precision' => [
            20,
            2,
          ],
          'where' => 'civicrm_case_sales_order_line.discounted_percentage',
          'table_name' => 'civicrm_case_sales_order_line',
          'entity' => 'CaseSalesOrderLine',
          'bao' => 'CRM_Civicase_DAO_CaseSalesOrderLine',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Discount"),
          ],
          'add' => NULL,
        ],
        'subtotal_amount' => [
          'name' => 'subtotal_amount',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Subtotal Amount'),
          'description' => E::ts('Quantity x Unit Price x (100-Discount)%'),
          'precision' => [
            20,
            2,
          ],
          'where' => 'civicrm_case_sales_order_line.subtotal_amount',
          'table_name' => 'civicrm_case_sales_order_line',
          'entity' => 'CaseSalesOrderLine',
          'bao' => 'CRM_Civicase_DAO_CaseSalesOrderLine',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Subtotal"),
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'case_sales_order_line', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'case_sales_order_line', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
