<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from uk.co.compucorp.civicase/xml/schema/CRM/Civicase/CaseSalesOrderContribution.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:714c7f79251d88e72e38c38e824131eb)
 */
use CRM_Civicase_ExtensionUtil as E;

/**
 * Database access object for the CaseSalesOrderContribution entity.
 */
class CRM_Civicase_DAO_CaseSalesOrderContribution extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicase_sales_order_contribution';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique CaseSalesOrderContribution ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to Case Sales Order
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $case_sales_order_id;

  /**
   * ID of Contribution
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $contribution_id;

  /**
   * Either percent ,i.e. certain percentage of the total_amount or remain, i.e. the remaining amount to be paid
   *
   * @var string
   *   (SQL type: varchar(20))
   *   Note that values will be retrieved from the database as a string.
   */
  public $to_be_invoiced;

  /**
   * The percentage value if to_be_invoiced is percent
   *
   * @var float|string
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $percent_value;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicase_sales_order_contribution';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Case Sales Order Contributions') : E::ts('Case Sales Order Contribution');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'case_sales_order_id', 'civicase_sales_order', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'contribution_id', 'civicrm_contribution', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique CaseSalesOrderContribution ID'),
          'required' => TRUE,
          'where' => 'civicase_sales_order_contribution.id',
          'table_name' => 'civicase_sales_order_contribution',
          'entity' => 'CaseSalesOrderContribution',
          'bao' => 'CRM_Civicase_DAO_CaseSalesOrderContribution',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'case_sales_order_id' => [
          'name' => 'case_sales_order_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Case Sales Order'),
          'required' => TRUE,
          'where' => 'civicase_sales_order_contribution.case_sales_order_id',
          'table_name' => 'civicase_sales_order_contribution',
          'entity' => 'CaseSalesOrderContribution',
          'bao' => 'CRM_Civicase_DAO_CaseSalesOrderContribution',
          'localizable' => 0,
          'FKClassName' => 'CRM_Civicase_DAO_CaseSalesOrder',
          'add' => NULL,
        ],
        'contribution_id' => [
          'name' => 'contribution_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('ID of Contribution'),
          'required' => TRUE,
          'where' => 'civicase_sales_order_contribution.contribution_id',
          'table_name' => 'civicase_sales_order_contribution',
          'entity' => 'CaseSalesOrderContribution',
          'bao' => 'CRM_Civicase_DAO_CaseSalesOrderContribution',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contribute_DAO_Contribution',
          'add' => NULL,
        ],
        'to_be_invoiced' => [
          'name' => 'to_be_invoiced',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('To Be Invoiced'),
          'description' => E::ts('Either percent ,i.e. certain percentage of the total_amount or remain, i.e. the remaining amount to be paid'),
          'required' => TRUE,
          'maxlength' => 20,
          'size' => CRM_Utils_Type::MEDIUM,
          'where' => 'civicase_sales_order_contribution.to_be_invoiced',
          'table_name' => 'civicase_sales_order_contribution',
          'entity' => 'CaseSalesOrderContribution',
          'bao' => 'CRM_Civicase_DAO_CaseSalesOrderContribution',
          'localizable' => 0,
          'add' => NULL,
        ],
        'percent_value' => [
          'name' => 'percent_value',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Percent Value'),
          'description' => E::ts('The percentage value if to_be_invoiced is percent'),
          'required' => FALSE,
          'precision' => [
            20,
            2,
          ],
          'where' => 'civicase_sales_order_contribution.percent_value',
          'default' => '0',
          'table_name' => 'civicase_sales_order_contribution',
          'entity' => 'CaseSalesOrderContribution',
          'bao' => 'CRM_Civicase_DAO_CaseSalesOrderContribution',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, '_sales_order_contribution', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, '_sales_order_contribution', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
